<?php

$conf = Mage::getStoreConfig('c2a_global/options');

$js_config = "";

if (1 == $conf['active']) {

	$design = Mage::getStoreConfig('c2a_global/design');
	$texts = Mage::getStoreConfig('c2a_global/texts');
	$advanced = Mage::getStoreConfig('c2a_global/advanced');

	$output = (object) array(
		'active' => $conf['active'],
		'access_token' => $conf['access_token'],
		'design' => (object) array(
			'mode' => $design['dropdown_mode'],
			'ambient' => $design['dropdown_ambient'],
			'accent' => $design['dropdown_accent']
		),
		'cc_hash_url' => Mage::getUrl('c2a/hash/save',array('_secure'=>true))
	);

} else { //if (1 == $conf['active']) {
	$output = (object) array(
		'active' => false
	);
}
?>

<script type="text/javascript">
//<![CDATA[
var c2a_config = <?php echo json_encode($output); ?>
//]]>
</script>
